services:
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: no
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "admin12345678"
    volumes:
      - ./data:/data
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address :9001
